version: "3.8"

services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true #Para o container identificar as alterações
      - NODE_ENV=development
      - VITE_PORT=5173
    command: ["npm", "run", "dev", "--", "--host"]
